// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountuserbinding"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AccountUserBindingCreate is the builder for creating a AccountUserBinding entity.
type AccountUserBindingCreate struct {
	config
	mutation *AccountUserBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountUserBindingCreate) SetCreatedAt(v time.Time) *AccountUserBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountUserBindingCreate) SetNillableCreatedAt(v *time.Time) *AccountUserBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountUserBindingCreate) SetUpdatedAt(v time.Time) *AccountUserBindingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountUserBindingCreate) SetNillableUpdatedAt(v *time.Time) *AccountUserBindingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountUserBindingCreate) SetAccountID(v int64) *AccountUserBindingCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AccountUserBindingCreate) SetUserID(v int64) *AccountUserBindingCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountUserBindingCreate) SetAccount(v *Account) *AccountUserBindingCreate {
	return _c.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *AccountUserBindingCreate) SetUser(v *User) *AccountUserBindingCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AccountUserBindingMutation object of the builder.
func (_c *AccountUserBindingCreate) Mutation() *AccountUserBindingMutation {
	return _c.mutation
}

// Save creates the AccountUserBinding in the database.
func (_c *AccountUserBindingCreate) Save(ctx context.Context) (*AccountUserBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountUserBindingCreate) SaveX(ctx context.Context) *AccountUserBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountUserBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountUserBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountUserBindingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountuserbinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountuserbinding.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountUserBindingCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountUserBinding.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountUserBinding.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountUserBinding.account_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AccountUserBinding.user_id"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountUserBinding.account"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AccountUserBinding.user"`)}
	}
	return nil
}

func (_c *AccountUserBindingCreate) sqlSave(ctx context.Context) (*AccountUserBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountUserBindingCreate) createSpec() (*AccountUserBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountUserBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountuserbinding.Table, sqlgraph.NewFieldSpec(accountuserbinding.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountuserbinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountuserbinding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserbinding.AccountTable,
			Columns: []string{accountuserbinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountuserbinding.UserTable,
			Columns: []string{accountuserbinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountUserBinding.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUserBindingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountUserBindingCreate) OnConflict(opts ...sql.ConflictOption) *AccountUserBindingUpsertOne {
	_c.conflict = opts
	return &AccountUserBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountUserBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountUserBindingCreate) OnConflictColumns(columns ...string) *AccountUserBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUserBindingUpsertOne{
		create: _c,
	}
}

type (
	// AccountUserBindingUpsertOne is the builder for "upsert"-ing
	//  one AccountUserBinding node.
	AccountUserBindingUpsertOne struct {
		create *AccountUserBindingCreate
	}

	// AccountUserBindingUpsert is the "OnConflict" setter.
	AccountUserBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUserBindingUpsert) SetUpdatedAt(v time.Time) *AccountUserBindingUpsert {
	u.Set(accountuserbinding.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUserBindingUpsert) UpdateUpdatedAt() *AccountUserBindingUpsert {
	u.SetExcluded(accountuserbinding.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountUserBindingUpsert) SetAccountID(v int64) *AccountUserBindingUpsert {
	u.Set(accountuserbinding.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUserBindingUpsert) UpdateAccountID() *AccountUserBindingUpsert {
	u.SetExcluded(accountuserbinding.FieldAccountID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AccountUserBindingUpsert) SetUserID(v int64) *AccountUserBindingUpsert {
	u.Set(accountuserbinding.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUserBindingUpsert) UpdateUserID() *AccountUserBindingUpsert {
	u.SetExcluded(accountuserbinding.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountUserBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountUserBindingUpsertOne) UpdateNewValues() *AccountUserBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountuserbinding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountUserBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountUserBindingUpsertOne) Ignore() *AccountUserBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUserBindingUpsertOne) DoNothing() *AccountUserBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountUserBindingCreate.OnConflict
// documentation for more info.
func (u *AccountUserBindingUpsertOne) Update(set func(*AccountUserBindingUpsert)) *AccountUserBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUserBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUserBindingUpsertOne) SetUpdatedAt(v time.Time) *AccountUserBindingUpsertOne {
	return u.Update(func(s *AccountUserBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUserBindingUpsertOne) UpdateUpdatedAt() *AccountUserBindingUpsertOne {
	return u.Update(func(s *AccountUserBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountUserBindingUpsertOne) SetAccountID(v int64) *AccountUserBindingUpsertOne {
	return u.Update(func(s *AccountUserBindingUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUserBindingUpsertOne) UpdateAccountID() *AccountUserBindingUpsertOne {
	return u.Update(func(s *AccountUserBindingUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountUserBindingUpsertOne) SetUserID(v int64) *AccountUserBindingUpsertOne {
	return u.Update(func(s *AccountUserBindingUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUserBindingUpsertOne) UpdateUserID() *AccountUserBindingUpsertOne {
	return u.Update(func(s *AccountUserBindingUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *AccountUserBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountUserBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUserBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountUserBindingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountUserBindingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountUserBindingCreateBulk is the builder for creating many AccountUserBinding entities in bulk.
type AccountUserBindingCreateBulk struct {
	config
	err      error
	builders []*AccountUserBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountUserBinding entities in the database.
func (_c *AccountUserBindingCreateBulk) Save(ctx context.Context) ([]*AccountUserBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountUserBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountUserBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountUserBindingCreateBulk) SaveX(ctx context.Context) []*AccountUserBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountUserBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountUserBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountUserBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUserBindingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountUserBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountUserBindingUpsertBulk {
	_c.conflict = opts
	return &AccountUserBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountUserBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountUserBindingCreateBulk) OnConflictColumns(columns ...string) *AccountUserBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUserBindingUpsertBulk{
		create: _c,
	}
}

// AccountUserBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountUserBinding nodes.
type AccountUserBindingUpsertBulk struct {
	create *AccountUserBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountUserBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountUserBindingUpsertBulk) UpdateNewValues() *AccountUserBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountuserbinding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountUserBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountUserBindingUpsertBulk) Ignore() *AccountUserBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUserBindingUpsertBulk) DoNothing() *AccountUserBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountUserBindingCreateBulk.OnConflict
// documentation for more info.
func (u *AccountUserBindingUpsertBulk) Update(set func(*AccountUserBindingUpsert)) *AccountUserBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUserBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountUserBindingUpsertBulk) SetUpdatedAt(v time.Time) *AccountUserBindingUpsertBulk {
	return u.Update(func(s *AccountUserBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountUserBindingUpsertBulk) UpdateUpdatedAt() *AccountUserBindingUpsertBulk {
	return u.Update(func(s *AccountUserBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountUserBindingUpsertBulk) SetAccountID(v int64) *AccountUserBindingUpsertBulk {
	return u.Update(func(s *AccountUserBindingUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountUserBindingUpsertBulk) UpdateAccountID() *AccountUserBindingUpsertBulk {
	return u.Update(func(s *AccountUserBindingUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountUserBindingUpsertBulk) SetUserID(v int64) *AccountUserBindingUpsertBulk {
	return u.Update(func(s *AccountUserBindingUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountUserBindingUpsertBulk) UpdateUserID() *AccountUserBindingUpsertBulk {
	return u.Update(func(s *AccountUserBindingUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *AccountUserBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountUserBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountUserBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUserBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
