// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountuserbinding"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountUserBindingDelete is the builder for deleting a AccountUserBinding entity.
type AccountUserBindingDelete struct {
	config
	hooks    []Hook
	mutation *AccountUserBindingMutation
}

// Where appends a list predicates to the AccountUserBindingDelete builder.
func (_d *AccountUserBindingDelete) Where(ps ...predicate.AccountUserBinding) *AccountUserBindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountUserBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountUserBindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountUserBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountuserbinding.Table, sqlgraph.NewFieldSpec(accountuserbinding.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountUserBindingDeleteOne is the builder for deleting a single AccountUserBinding entity.
type AccountUserBindingDeleteOne struct {
	_d *AccountUserBindingDelete
}

// Where appends a list predicates to the AccountUserBindingDelete builder.
func (_d *AccountUserBindingDeleteOne) Where(ps ...predicate.AccountUserBinding) *AccountUserBindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountUserBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountuserbinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountUserBindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
